### ISSUE TITLE
pysendfile does not compile on Python 3.4

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/pysendfile#22]
```
giampaolo@UX32VD:~/svn/pysendfile$ make test PYTHON=python3.4
rm -f `find . -type f -name \*.py[co]`
rm -f `find . -type f -name \*.so`
rm -f `find . -type f -nam1e .\*~`
find: unknown predicate `-nam1e'
rm -f `find . -type f -name \*.orig`
rm -f `find . -type f -name \*.bak`
rm -f `find . -type f -name \*.rej`
rm -rf `find . -type d -name __pycache__`
rm -rf *.egg-info
rm -rf *\estfile*
rm -rf .tox
rm -rf build
rm -rf dist
rm -rf docs/_build
python3.4 setup.py build
running build
running build_ext
building 'sendfile' extension
creating build
creating build/temp.linux-x86_64-3.4
gcc -pthread -Wno-unused-result -Werror=declaration-after-statement -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.4m -c sendfilemodule.c -o build/temp.linux-x86_64-3.4/sendfilemodule.o
sendfilemodule.c: In function ‘PyInit_sendfile’:
sendfilemodule.c:395:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
     struct module_state *st = GETSTATE(module);
     ^
cc1: some warnings being treated as errors
error: command 'gcc' failed with exit status 1
make: *** [build] Error 1
```
